import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed-dim": "#ffb870",
        "primary-fixed": "#d6e3ff",
        "on-secondary-container": "#626567",
        "on-primary": "#ffffff",
        "on-primary-container": "#c8daff",
        "surface-container": "#e5eeff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed": "#ffdcbe",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed": "#2d1600",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#424750",
        "tertiary": "#6b3c00",
        "primary": "#08478a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#693c00",
        "on-error": "#ffffff",
        "secondary-container": "#e0e3e5",
        "on-background": "#0b1c30",
        "background": "#f8f9ff",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e0e3e5",
        "secondary": "#5c5f61",
        "inverse-surface": "#213145",
        "primary-fixed-dim": "#a9c7ff",
        "on-secondary-fixed": "#191c1e",
        "on-primary-fixed": "#001b3d",
        "inverse-primary": "#a9c7ff",
        "tertiary-container": "#8c5100",
        "on-error-container": "#93000a",
        "on-surface": "#0b1c30",
        "primary-container": "#2e5fa3",
        "on-secondary-fixed-variant": "#444749",
        "outline-variant": "#c3c6d2",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffd1a8",
        "surface-variant": "#d3e4fe",
        "secondary-fixed-dim": "#c4c7c9",
        "on-primary-fixed-variant": "#074689",
        "outline": "#737782",
        "surface-tint": "#2d5ea2",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "24px",
        md: "16px",
        base: "4px",
        sm: "8px",
        xs: "4px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "code-sm": ["Inter", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      boxShadow: {
        "card": "0px 1px 3px rgba(0,0,0,0.05), 0px 4px 6px rgba(0,0,0,0.02)",
        "soft": "0px 1px 3px rgba(0,0,0,0.05), 0px 4px 6px rgba(0,0,0,0.02)",
        "deep": "0px 10px 15px -3px rgba(0,0,0,0.1)",
        "elevated": "0 4px 20px rgba(8,71,138,0.08)",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(16px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-16px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.6" },
        },
        "count-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.4s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards",
        "slide-in-left": "slide-in-left 0.3s ease-out forwards",
        "scale-in": "scale-in 0.2s ease-out forwards",
        "shimmer": "shimmer 2s infinite linear",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        "count-up": "count-up 0.5s ease-out forwards",
      },
    },
  },
  plugins: [],
};

export default config;
